apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login$', views.login),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register),
    url(r'^user/(?P<user_id>\d+)$', views.show)
]

apps/review/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add$', views.add, name="add"),
    url(r'^create', views.create, name="create"),
    url(r'^(?P<book_id>\d+)$', views.show),
    url(r'^(?P<book_id>\d+)/create$', views.create_additional)
]

beltReview/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^books/', include('apps.review.urls', namespace='review')),
]

apps/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')


class UserManager(models.Manager):
    def validate_login(self, check_user):
        errors = ""
        if len(self.filter(email=check_user['email'])) > 0:
            user = self.filter(email=check_user['email'])[0]
            if not bcrypt.checkpw(check_user['password'].encode(), user.password.encode()):
                errors="Incorrect Password"
        else:
            errors="Incorrect Email"

        return errors

    def validate_registration(self,user):
        errors=[]

        if len(user['name']) < 2:
            errors.append("First Name must have more than two characters")
        if len(user['user_name'])<2:
            errors.append("Last Name must have more than two characters")
        if len(user['password']) < 8:
            errors.append("password must be at least 8 characters")
        if not re.match(EMAIL_REGEX, user['email']):
            errors.append("Invalid email")
        if len(User.objects.filter(email=user['email'])) > 0:
            errors.append("email already in use")
        if user['password'] != user['password_confirm']:
            errors.append("passwords do not match")
        if len(User.objects.filter(user_name=user['user_name'])) > 0:
            errors.append("Username already in use")

        return errors

class User(models.Model):
    name = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    objects = UserManager()
    def __str__(self):
        return self.email

apps/review/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..login.models import User
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, related_name="books")
    def __str__(self):
        return self.title

class ReviewManager(models.Manager):
    def validate_review(self, post_data):
        errors = []

        if len(post_data['title']) < 1 or len(post_data['review']) < 1:
            errors.append('fields are required')
        if not "author" in post_data and len(post_data['new_author']) < 3:
            errors.append('new author names must 3 or more characters')

        if "author" in post_data and len(post_data['new_author']) > 0 and len(post_data['new_author']) < 3:
            errors.append('new author names must 3 or more characters')
        if not int(post_data['rating']) > 0 or not int(post_data['rating']) <= 5:
            errors.append('invalid rating')
        return errors

    def create_review(self, clean_data, email):
        # retrive or create author
        the_author = None
        if len(clean_data['new_author']) < 1:
            the_author = Author.objects.get(id=int(clean_data['author']))
        else:
            the_author = Author.objects.create(name=clean_data['new_author'])
        # retirive or create book
        the_book = None
        if not Book.objects.filter(title=clean_data['title']):
            the_book = Book.objects.create(
                title=clean_data['title'], author=the_author
            )
        else:
            the_book = Book.objects.get(title=clean_data['title'])
        self.create(
            review = clean_data['review'],
            rating = clean_data['rating'],
            book = the_book,
            reviewer = User.objects.get(email=email)
        )

    def recent_and_not(self):
        '''
        returns a tuple with the zeroeth index containing query for 3 most recent reviews, and the first index
        containing the rest
        '''
        return (self.all().order_by('-created_at')[:3], self.all().order_by('-created_at')[3:])

class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name="reviews")
    reviewer = models.ForeignKey(User, related_name="reviews_left")
    created_at = models.DateTimeField(auto_now_add=True)
    objects = ReviewManager()
    def __str__(self):
        return "Book: (self.book.title)"

apps/login/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,reverse
import re
from .models import User
import bcrypt
from django.contrib import messages
from ..review.models import Book




def index(request):
    return render(request, 'login/index.html')

def login(request):
    user={}
    for key,value in request.POST.items():
        if key!="csrfmiddlewaretoken":
            user[key]=value

    errors = User.objects.validate_login(user)
    if len(errors)>0:
        messages.error(request, errors)
        return redirect('/')
    request.session['email'] = user['email']
    return HttpResponseRedirect(reverse("review:index"))

def register(request):
    new_user={}
    for key,value in request.POST.items():
        if key!="csrfmiddlewaretoken":
            new_user[key]=value
    errors = User.objects.validate_registration(new_user)
    if errors:
        for message in errors:
            messages.error(request, message)
        return redirect('/')


    hashed = bcrypt.hashpw((new_user['password'].encode()), bcrypt.gensalt(5))
    User.objects.create(
        name=new_user['name'],
        user_name=new_user['user_name'],
        email=new_user['email'],
        password=hashed
        )
    messages.success(request, "Successfully registered! Please Login Now")
    return redirect('/')

def logout(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect('/')


def show(request, user_id):
    user = User.objects.get(id=user_id)
    book_ids = user.reviews_left.all().values("book").distinct()
    user_books = []
    for book in book_ids:
        user_books.append(Book.objects.get(id=book['book']))
    context = {
        'user': user,
        'unique_book_reviews': user_books
    }
    return render(request, 'login/show.html', context)

apps/review/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Review, Author, Book
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
def index(request):
    context = {
        'recent': Review.objects.recent_and_not()[0],
        'more': Review.objects.recent_and_not()[1]
    }
    return render(request, 'review/index.html', context)

def add(request):
    context = {
        "authors": Author.objects.all()
    }
    return render(request, 'review/add.html', context)

def show(request, book_id):
    context = {
        'book': Book.objects.get(id=book_id)
    }
    return render(request, 'review/show.html', context)

def create(request):
    errs = Review.objects.validate_review(request.POST)
    if errs:
        for e in errs:
            messages.error(request, e)
    else:
        Review.objects.create_review(request.POST, request.session['email'])
    return redirect('/books')

def create_additional(request, book_id):
    print book_id, type(book_id)
    the_book = Book.objects.get(id=book_id)
    new_book_data = {
        'title': the_book.title,
        'author': the_book.author.id,
        'rating': request.POST['rating'],
        'review': request.POST['review'],
        'new_author': ''
    }
    errs = Review.objects.validate_review(new_book_data)
    if errs:
        for e in errs:
            messages.error(request, e)
    else:
        Review.objects.create_review(new_book_data, request.session['email'])
    return redirect('/books/' + book_id)

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Welcome</h1>
  {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
  {% endif %}
   <h2>Registration</h2>
   <form action="/register" method="POST">
       {% csrf_token %}
       <div class="form-group">
           <label for="name">Name</label>
           <input type="text" name="name">
       </div>
       <div class="form-group">
           <label for="user_name">User Name:</label>
           <input type="text" name="user_name">
       </div>
       <div class="form-group">
           <label for="email">Email</label>
           <input type="email" name="email">
       </div>
       <div class="form-group">
           <label for="password">Password</label>
           <input type="password" name="password">
       </div>
       <div class="form-group">
           <label for="password_confirm">Confirm Password</label>
           <input type="password" name="password_confirm">
       </div>
       <input type="submit" value='Register'>
   </form>
   <h2>Login</h2>
   <form action="/login" method="POST">
       {% csrf_token %}
       <div class="form-group">
           <label for="email">Email</label>
           <input type="email" name="email">
       </div>
       <div class="form-group">
           <label for="password">Password</label>
           <input type="password" name="password">
       </div>
       <input type="submit" value='Login'>
   </form>

</body>
</html>

apps/login/templates/login/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<p><a href="/books">Home</a> | <a href="{% url 'review:add' %}">Add book and review</a> | <a href="/logout">Logout</a></p>
<h1><strong>User Name: </strong>{{user.user_name}}</h1>
<h2><strong>Name: </strong> {{user.name}}</h2>
<h2><strong>Email: </strong> {{user.email}}</h2>
<h2><strong>Total Reviews: </strong> {{user.reviews_left.all.count}}</h2>
<hr>
<h1>Posted Reviews on the Folowing Books</h1>
{% for book in unique_book_reviews %}
<h3><a href="/books/{{book.id}}">{{book.title}}</a></h3>
{% endfor %}
</body>
</html>

apps/review/templates/review/add.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'review/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <p><a href="/books">Home</a> | <a href="/logout">Logout</a></p>
        <h1>ADD A REVIEW</h1>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <form action="/books/create" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Book Title:</label>
                <input type="text" name="title">
            </div>
            <div class="form-group">
                <label for="author">Author:</label>
                <span>Choose from the list:</span>
                <select name="author">
                    {% for author in authors %}
                        <option value="{{author.id}}">{{author.name}}</option>
                    {% endfor %}
                </select>
                <span>Or add a new author:</span>
                <input type="text" name="new_author">
            </div>
            <div class="form-group">
                <label for="review">Review:</label>
                <textarea rows="5" cols="40" type="text" name="review"></textarea>
            </div>
            <div class="form-group">
                <label for="rating">Rating</label>
                <select name="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <input type="submit" value="Add Book and Review">
        </form>
    </body>
</html>

apps/review/templates/review/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'review/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <h2>Welcome {{ user.name}}</h2>
            <p><a href="{% url 'review:add' %}">Add book and review</a> | <a href="{% url 'login:logout' %}">Logout</a></p>

        </header>
        <div class="main">
            <h2>Recent Book Reviews:</h2>
            {% for review in recent %}
            <div class="review">
                <h2><a href="/books/{{review.book.id}}">{{ review.book.title }}</a></h2>
                <p>Rating: {{ review.rating }}</p>
                <p><a href="/user/{{review.reviewer.id}}">{{ review.reviewer.name}}</a> says: {{ review.review }}</p>
                <p>Posted on: {{ review.created_at }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="side">
            <h2>Other Books with Reviews:</h2>
            {% for review in more %}
            <div class="review">
                <h2><a href="/books/{{review.book.id}}">{{ review.book.title }}</a></h2>
            </div>
            {% endfor %}
        </div>
    </body>
</html>

apps/review/templates/review/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'review/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <p><a href="/books">Home</a> | <a href="/logout">Logout</a></p>
        <h1>{{book.title}}</h1>
        <h2>{{book.author}}</h2>
        <div class="reviews">
            <h3>Reviews:</h3>
            <hr>
            {% for review in book.reviews.all %}
                <p>Rating: {{review.rating}}</p>
                <p><a href="/user/{{review.reviewer.id}}">{{review.reviewer.name}}</a> says: {{review.review}}</p>
            <p>Posted on: {{review.created_at}}</p>
            <hr>
            {% endfor %}
        </div>
        <form action="/books/{{book.id}}/create" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="review">Review:</label>
                <textarea rows="5" cols="40" type="text" name="review"></textarea>
            </div>
            <div class="form-group">
                <label for="rating">Rating</label>
                <select name="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <input type="submit" value="Submit Review">
        </form>
    </body>
</html>